Project/Project/Controllers/MKTController.cs
using Project.Filter;
using Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models.manage;
using System.IO;

namespace Project.Controllers
{
    public class RevenuesOfCategory1
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int Revenue { get; set; }
    }
    public class MKTModel : MarketingCommonViewModel
    {
        public int Posts { get; set; }
        public int Product { get; set; }
        public int Feedback { get; set; }
        public int TotalRevenues { get; set; }
        public IEnumerable<RevenuesOfCategory> RevenuesCategories { get; set; }
        public double AverageStar { get; set; }
        public int NewAccount { get; set; }
        public IEnumerable<Account> NewMember { get; set; }
        public HotTrend Trend { get; set; }
    }

    public class PostViewModelz
    {
        public int Id { get; set; }
        public DateTime? DateCreate { get; set; }
        public DateTime? DateUpdate { get; set; }
        public string AuthorName { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Detail { get; set; }
        public int CountView { get; set; }
    }

    public class MKTPost : MarketingCommonViewModel
    {
        public PostViewModelz PostDetail { get; set; }
        public Account Author { get; set; }

        public Blog EditPost { get; set; }
    }
    public class MKTProductDetail : MarketingCommonViewModel
    {
        public Product Products { get; set; }
        public Category Categories { get; set; }
        public IEnumerable<ProductCategory> ProductCategory { get; set; }
        public IEnumerable<ImageProduct> ImageProducts { get; set; }
    }
    public class PostListViewModelz : MarketingCommonViewModel
    {
        public IEnumerable<PostViewModelz> Posts { get; set; }
        public IEnumerable<Account> Authors { get; set; }
    }
    public class MKTCustomer : MarketingCommonViewModel
    {
        public Account Customer { get; set; }
    }

    public class MKTFeedbackDetail : MarketingCommonViewModel
    {
        public Feedback Feedback { get; set; }
        public ImageFeedback ImageFeedback { get; set; }
        public Account CustomerFeedback { get; set; }
        public Product FeedbackProductImage { get; set; }
    }

   
    public class MKTProductDetailz 
    {
        public Product Product { get; set; }
        public List<string> Images { get; set; }
        public List<Category> Categories { get; set; }

        public MKTProductDetailz(Product product, List<string> images, List<Category> categories)
        {
            Product = product;
            Images = images;
            Categories = categories;
        }
    }
   
    public class MKTProductDetailList : MarketingCommonViewModel
    {
        public List<MKTProductDetailz> MKTProductDetails { get; set; }

        public MKTProductDetailList()
        {
        }

        public MKTProductDetailList(List<MKTProductDetailz> mKTProductDetails)
        {
            MKTProductDetails = mKTProductDetails;
        }
    }

    [AuthenticationFilter]
    [AuthorizationFilter(role: "marketing")]
    public class MKTController : Controller
    {
        private ProjectEntities db = new ProjectEntities();
        // GET: MKT
        [AuthenticationFilter]
        [AuthorizationFilter(role: "marketing")]
        public ActionResult Dashboard(DateTime? from, DateTime? to)
        {
            MKTModel mktmodel = new MKTModel();
            mktmodel.Title = "Dashboard";
            mktmodel.Tab = TabEnumMkt.Dashboard;

            if (from != null && to != null)
            {
                mktmodel.NewAccount = db.Accounts.Where(a => a.CreatedAt >= from && a.CreatedAt <= to).Count(a => a.IsActive == true);
                mktmodel.Posts = db.Sliders.Where(a => a.CreatedAt >= from && a.CreatedAt <= to).Count();
                mktmodel.Product = db.Products.Where(a => a.CreatedAt >= from && a.CreatedAt <= to).Count();
                mktmodel.Feedback = db.Feedbacks.Where(a => a.CreatedAt >= from && a.CreatedAt <= to).Count();

                mktmodel.TotalRevenues = (db.OrderDetails.Where(a => a.CreatedAt >= from && a.CreatedAt <= to)).Sum(a => a.SalePrice);

                mktmodel.AverageStar = db.Feedbacks.Average(a => a.RateStar);
                mktmodel.NewMember = db.Accounts.OrderByDescending(a => a.Id).Where(a => a.IsActive == true && a.Role == 0 && a.CreatedAt >= from && a.CreatedAt <= to).Take(5);
                mktmodel.RevenuesCategories = (from s in db.OrderDetails // outer sequence
                                               join c in db.ProductCategories//inner sequence 
                                               on s.ProductId equals c.ProductId
                                               group c by c.CategoryId into r
                                               select new RevenuesOfCategory
                                               {
                                                   CategoryName = r.FirstOrDefault().Category.Title == null ? "Co the la null" : r.FirstOrDefault().Category.Title,
                                                   Revenue = r.Sum(s => s.Product.SalePrice)


                                               }).ToList();
                mktmodel.Trend = db.OrderDetails.GroupBy(o => o.ProductId).Select(group => new HotTrend
                { ProductName = group.FirstOrDefault().Product.Title, Count = group.Count() }).
                OrderByDescending(x => x.Count).FirstOrDefault();
            }
            else
            {

                mktmodel.NewAccount = db.Accounts.Count(a => a.IsActive == true);
                mktmodel.Posts = db.Sliders.Count();
                mktmodel.Product = db.Products.Count();
                mktmodel.Feedback = db.Feedbacks.Count();
                mktmodel.TotalRevenues = db.OrderDetails.Sum(t => t.SalePrice);
                mktmodel.AverageStar = db.Feedbacks.Average(a => a.RateStar);
                mktmodel.NewMember = db.Accounts.OrderByDescending(a => a.Id).Where(a => a.IsActive == true && a.Role == 0).Take(5);
                mktmodel.RevenuesCategories = (from s in db.OrderDetails // outer sequence
                                               join c in db.ProductCategories//inner sequence 
                                               on s.ProductId equals c.ProductId
                                               group c by c.CategoryId into r
                                               select new RevenuesOfCategory
                                               {
                                                   CategoryId = r.Key,
                                                   CategoryName = r.FirstOrDefault().Category.Title == null ? "Co the la null" : r.FirstOrDefault().Category.Title,
                                                   Revenue = r.Sum(s => s.Product.SalePrice)


                                               }).ToList();
                mktmodel.Trend = db.OrderDetails.GroupBy(o => o.ProductId).Select(group => new HotTrend
                { ProductName = group.FirstOrDefault().Product.Title, Count = group.Count() }).
                OrderByDescending(x => x.Count).FirstOrDefault();
            }

            return View(mktmodel);
        }
        [AuthenticationFilter]
        [AuthorizationFilter(role: "marketing")]
        public ActionResult PostDetail(int? id)
        {
            MKTPost model = new MKTPost();
            model.Title = "Post Detail";
            model.Tab = TabEnumMkt.Post;
            model.PostDetail = db.Blogs.Join(db.Accounts, (b => b.AuthorId), (a => a.Id), (b, a) => new PostViewModelz

            {

                Id = b.Id,

                AuthorName = a.FullName,

                Title = b.Title,

                Image = b.Image,

                Detail = b.Detail,

                CountView = b.CountView

            }).Where(p => p.Id == id).First();

            return View(model);
        }
        [HttpGet]
        public ActionResult PostEdit(int? id)
        {
            MKTPost model = new MKTPost();
            model.Title = "Post Edit";
            model.Tab = TabEnumMkt.Post;
            model.PostDetail = db.Blogs.Join(db.Accounts, (b => b.AuthorId), (a => a.Id), (b, a) => new PostViewModelz
            {

                Id = b.Id,

                AuthorName = a.FullName,

                Title = b.Title,

                Image = b.Image,

                Detail = b.Detail,

                CountView = b.CountView

            }).Where(p => p.Id == id).First();
            return View(model);
        }

        /*[AuthenticationFilter]
        [AuthorizationFilter(role: "marketing")]*/
        public ActionResult CustomerDetail(int? id)
        {
            MKTCustomer customer = new MKTCustomer();
            customer.Title = "Customer Detail";
            customer.Tab = TabEnumMkt.Customer;
            customer.Customer = db.Accounts.Where(c => c.Id == id).FirstOrDefault();
            return View(customer);
        }
        [HttpGet]
        public ActionResult CustomerEdit(int? id)
        {
            MKTCustomer customer = new MKTCustomer();
            customer.Title = "Customer Edit";
            customer.Tab = TabEnumMkt.Customer;
            customer.Customer = db.Accounts.Where(c => c.Id == id).FirstOrDefault();
            return View(customer);
        }

        [HttpPost]
        public ActionResult CustomerEdit(int? id, bool status)
        {
            MKTCustomer customer = new MKTCustomer();

Project/Project/Views/MKT/AddImg.cshtml
@{
    ViewBag.Title = "AddImg";
    Layout = "~/Views/Shared/_MarketingLayout.cshtml";
}

<h2>AddImg</h2>

Project/Project/Views/MKT/CustomerEdit.cshtml
@{
    ViewBag.Title = "CustomerEdit";
    Layout = "~/Views/Shared/_MarketingLayout.cshtml";
}


@model Project.Controllers.MKTCustomer

<div class="card">
    @using (Html.BeginForm("CustomerEdit", "MKT", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row g-0" style="height:auto">
            <div class="col-md-6 border-end">
                <div class="d-flex flex-column justify-content-center">
                    <img src="@Model.Customer.Image" id="main_product_image" class="imgd">
                </div>

            </div>
            <div class="col-md-6">
                <div class="p-3 right-side">
                    <h4>FullName</h4>
                    <div class="input-group mb-3">
                        <p> @Model.Customer.FullName</p>
                    </div>
                    <h4>Email</h4>
                    <div class="input-group mb-3">
                        <p> @Model.Customer.Email</p>
                    </div>
                    <h4>Phone Number</h4>
                    <div class="input-group mb-3">
                        <p> @Model.Customer.Phone</p>
                    </div>
                    <h4>Address</h4>
                    <div class="input-group mb-3">
                        <p> @Model.Customer.Address</p>
                    </div>
                    <h4>Status</h4>
                    <div class="input-group mb-3">
                        @if (Model.Customer.IsActive == true) {
                            <select name="status">
                                    <option value="true" selected>Online</option>
                                    <option value="false">Offline</option>
                            </select>
                        }
                        else
                         {
                            <select name="status" >
                                    <option value="true">Online</option>
                                    <option value="false" selected>Offline</option>
                            </select>
                        }

                    </div>
                    <div class="buttons d-flex flex-row mt-5 gap-3">
                        <button class="btn btn-dark" type="submit">Save</button>

                    </div>

                </div>
            </div>
        </div>
    }
</div>

Project/Project/Views/MKT/PostEdit.cshtml
@{
    ViewBag.Title = "PostEdit";
    Layout = "~/Views/Shared/_MarketingLayout.cshtml";
}
@model Project.Controllers.MKTPost
<link href="~/Content/blog/postdetail.css" rel="stylesheet" />
<div class="card">
    @using (Html.BeginForm("PostEdit", "MKT", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row g-0" style="height:auto">
            <div class="col-md-6 border-end">
                <div class="d-flex flex-column justify-content-center">
                    <img src="@Model.PostDetail.Image" id="main_product_image" class="imgd" style="width:auto;max-height:800px;">
                    <div class="input-group" style="padding: 10px 10px 10px 10px;">
                        <input type="file" id="imgold" class="form-control" aria-label="Upload" name="image" accept="image/*" onfocus="focused(this)" onfocusout="defocused(this)">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="p-3 right-side">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3>Title</h3>
                    </div>
                    <div class="input-group">
                        <input type="text" name="title" value="@Model.PostDetail.Title" required="" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)">
                    </div>
                    <h3>Detail</h3>

                    <div class="mt-2 pr-3 content">
                        <textarea style="height:250px;" name="detail" class="form-control" aria-label="With textarea">@Model.PostDetail.Detail</textarea>

                    </div>
                    <h3>Author</h3>
                    <div class="input-group mb-3">
                        <p> @Model.PostDetail.AuthorName</p>
                    </div>
                    <div class="ratings d-flex flex-row align-items-center">
                        <i class="bi bi-eye-fill"></i> <span>@Model.PostDetail.CountView views</span>
                    </div>
                    <div class="buttons d-flex flex-row mt-5 gap-3">
                        <a class="btn btn-outline-dark" onclick="history.go(-1)">Back</a>
                        <button class="btn btn-dark" type="submit">Save</button>

                    </div>

                </div>
            </div>
        </div>
    }
</div>
<script>
    const imgold = document.getElementById('imgold');
    const imgnew = document.getElementById('main_product_image');
    imgold.onchange = evt => {
        const [file] = imgold.files
        if (file) {
            imgnew.src = URL.createObjectURL(file)
        }
    }
</script>

Project/Project/Views/MKT/PostList.cshtml
@model Project.Controllers.PostListViewModelz
@{

    Layout = "~/Views/Shared/_MarketingLayout.cshtml";
}
<link rel="stylesheet" href="~/Content/style.css" />
<link rel="stylesheet" href="~/Content/blog/blogList.css" />
<link href="~/Content/blog/postdetail.css" rel="stylesheet" />
@{
    var message = TempData["successmessage"] ?? string.Empty;
}

<script type="text/javascript">
var message = '@message';
if(message)
    alert(message)

</script>
<h2>Post List </h2>
<div class="card">
    <div style="padding: 10px 10px 10px 10px" class="row">
        <div class="col-lg-12">
            <section class="widget">
                <header>

                    <div>
                        @using (Html.BeginForm("SearchPost", "MKT", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {


                            <div style="display:inline-block">
                                <div style="color: #67748e">Filter by Author</div>
                                <select id="author" name="author" class="form-select">
                                    <option value="" selected>
                                        Select Author
                                    </option>
                                    @foreach (var item in Model.Authors)
                                    {
                                        if (item.Id == ViewBag.AuthorId)
                                        {
                                            <option value="@item.Id" selected>@item.FullName</option>
                                        }
                                        else
                                        {
                                            <option value="@item.Id">@item.FullName</option>
                                        }
                                    }
                                </select>
                            </div>


                            <div style="display:inline-block; padding-left: 10px;">
                                <div style="color: #67748e ">Search by Id or name </div>
                                <div><input id="idOrName" name="idOrName" type="search" class="form-control rounded" value="@(String.IsNullOrEmpty(ViewBag.idOrName) == true?"":ViewBag.idOrName)" placeholder="Search" /></div>
                            </div>
                            <div style="display:inline-block"><input type="submit" style="background-color:lightgray;margin-top:1rem" class="btn btn-default" value="Search" /></div>
                            <div style="display:inline-block;float:right;margin-right:70px">
                                <a style="margin-top:1rem" class="btn btn-primary" data-bs-toggle="modal" href="#exampleModalToggle" role="button">Create post</a>
                            </div>
                        }

                    </div>

                </header>
                <div class="widget-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="d-none d-md-table-cell">#</th>
                                    <th>Image</th>
                                    <th>Title</th>
                                    <th class="d-none d-md-table-cell">Author</th>
                                    <th class="d-none d-md-table-cell">Status</th>
                                    <th>Date Created</th>
                                    <th>Date Updated</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @{
                                    string a = "";
                                }
                                @foreach (var item in (Model.Posts))
                                {
                                    <tr>
                                        <td class="d-none d-md-table-cell">@item.Id</td>
                                        <td>
                                            <a href="/MKT/PostDetail/@item.Id"><img class="img-rounded" src="@item.Image" alt="" height="50"></a>

                                        </td>
                                        <td style="white-space:normal">
                                            <a href="/MKT/PostDetail/@item.Id">@item.Title</a>
                                        </td>

                                        <td class="d-none d-md-table-cell text-semi-muted">
                                            @item.AuthorName
                                        </td>
                                        <td>
                                            @if (item.CountView > 2000)
                                            {
                                                <span class="badge badge-danger">Hot</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-success">Trending</span>
                                            }
                                        </td>
                                        <td class="d-none d-md-table-cell">
                                            @item.DateCreate
                                        </td>
                                        <td class="d-none d-md-table-cell">
                                            @item.DateUpdate
                                        </td>                                      
                                        <td class="width-150">
                                            <a class="btn btn-secondary" href="/MKT/PostEdit/@item.Id">Edit</a>
                                            <a class="btn btn-danger" data-bs-toggle="modal" href="@("#Modal"+item.Id)" role="button">Delete</a>
                                            <div class="modal" id="@("Modal"+item.Id)" aria-hidden="true" aria-labelledby="@("Modal"+item.Id)">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content" style="width:auto;">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title text-center" id="@("Modal"+item.Id)">Delete</h5>
                                                            <button data-bs-dismiss="modal" aria-label="Close">X</button>
                                                        </div>
                                                        <div class="modal-body">                                                           
                                                            <h6 class="text-center">Are you want to delete @item.Title ?</h6>

                                                            <a class="btn btn-outline-dark" data-bs-dismiss="modal" aria-label="Close">Cancel</a>
                                                            <a class="btn btn-danger" href="/MKT/DeletePost/@item.Id/@ViewBag.Index">Delete</a>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>

                                    </tr>
                                }

                            </tbody>

                        </table>
                    </div>

                </div>
            </section>
        </div>
    </div>
</div>
<style>
    .blog-pagination a {
        color: #67748e;
        font-weight: bold;
    }
</style>

<div class="blog-pagination">
    @if (ViewBag.Index != null && ViewBag.Index > 1)
    {
        <a href="/MKT/PostList?id=@(ViewBag.Index-1)&authorId=@ViewBag.AuthorId&idOrName=@ViewBag.idOrName">Previous</a>
    }
    else
    {
        <a href="#">Previous</a>
    }

    @for (double i = 1; i < (((double)ViewBag.count / 7)+1); i++)
    {
        if (i == ViewBag.Index)
        {
            <a style="background-color:khaki" href="/MKT/PostList?id=@(i)&authorId=@ViewBag.AuthorId&idOrName=@ViewBag.idOrName">@i</a>
        }
        else
        {
            <a href="/MKT/PostList?id=@(i)&authorId=@ViewBag.AuthorId&idOrName=@ViewBag.idOrName">@i</a>
        }

    }
    @if (ViewBag.Index != null && ViewBag.Index * 7 < ViewBag.count)
    {
        <a href="/MKT/PostList?id=@(ViewBag.Index + 1)&authorId=@ViewBag.AuthorId&idOrName=@ViewBag.idOrName">Next</a>
    }
    else
    {
        <a href="#">Next</a>
    }
</div>

<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalToggleLabel">Create post</h5>
                <button class="btn btn-close" data-bs-dismiss="modal" aria-label="Close">X</button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("CreatePost", "MKT", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div>
                        <label>Title of Post</label>
                        <input type="text" id="Title" name="Title" class="form-control" placeholder="Enter Title">
                    </div>

                    <div>
                        <label>Author</label>
                        <select id="Author" name="Author" class="form-select">
                            <option selected>Select Author</option>
                            @foreach (var item in Model.Authors)
                            {
                                <option value="@item.Id">@item.FullName</option>
                            }
                        </select>
                    </div>

                    <div>
                        <label> Detail </label>
                        <textarea name="Detail" id="Detail" class="form-control" placeholder="Enter detail"></textarea>
                    </div>
                    <div>
                        <label> Upload image </label>
                        <input type="file" id="File" class="form-control" aria-label="Upload" name="File" accept="image/*" onfocus="focused(this)" onfocusout="defocused(this)">

                    </div>
                    <div>
                        <input class="btn btn-primary" type="submit" value="Add" />
                    </div>
                }

            </div>
        </div>
    </div>
</div>



Project/Project/Views/MKT/ProductEdit.cshtml
@{
    ViewBag.Title = "ProductEdit";
    Layout = "~/Views/Shared/_MarketingLayout.cshtml";
}
@model Project.Controllers.MKTProductDetail

<link href="~/Content/blog/postdetail.css" rel="stylesheet" />
<link href="~/Content/product/product1.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" />
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" />

<style>
    #file{
        display:none;
    }
    .imgz {
        width: auto;
        height: auto;
        padding: 10px;
        min-width: 600px;
        max-height: 500px;
    }
</style>

<div class="card">
    
    <div class="row g-0" style="height:auto">
        <div class="col-md-6 border-end">
            <div class="d-flex flex-column justify-content-center">
                <div class="main_image" style="height:auto;">
                    <img  class="imgz"
                         src="@Model.ProductCategory.FirstOrDefault().Product.ImageProducts.First().Image"
                         id="main_product_image" />
                </div>
                <div class="thumbnail_images">
                    <ul id="thumbnail">
                        @foreach (var img in Model.ProductCategory.FirstOrDefault().Product.ImageProducts)
                        {

                            <li class="card1">
                                <a class="badge bg-black text-dark position-absolute" onclick="deleteimg(@img.Id)" style="top: 0.2rem; right: 0.2rem">X</a>
                                <img onclick="changeImage(this)"
                                     src="@img.Image"
                                     id="imgid"
                                    
                                     width="70" />
                            </li>
                        }

                    </ul>
                    @using (Html.BeginForm("AddImg", "MKT", FormMethod.Post, new { enctype = "multipart/form-data"}))
                    {
                        <input type="file" class="inline" style="width:300px;" id="newimg" aria-label="Upload" name="image" accept="image/*" onfocus="focused(this)" accept=".jpg, .png, .jpeg" onfocusout="defocused(this)"> <button class="inline btn btn-secondary ">ADD</button>
                    }


                    </div>
            </div>
        </div>
       
        <div class="col-md-6">
            @using (Html.BeginForm("ProductEdit", "MKT", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="p-3 right-side">
                    <h3>Title</h3>
                    <div class="d-flex justify-content-between align-items-center">
                        <input type="text" name="title" value="@Model.ProductCategory.First().Product.Title" required="" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)">
                    </div>
                    <h3>Detail</h3>

                    <div class="mt-2 pr-3 content">
                        <textarea style="height:200px;" name="detail" class="form-control" aria-label="With textarea">@Model.ProductCategory.First().Product.Detail</textarea>
                    </div>
                    <h3>Price</h3>
                    <div class="mt-2 pr-3 content">
                        <a> Sale price:   <input type="text" name="sale" value="@Model.ProductCategory.First().Product.SalePrice" required="" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)"></a>
                        <br />
                        <a> Original price:  <input type="text" name="original" value="@Model.ProductCategory.First().Product.OriginalPrice" required="" class="form-control" onfocus="focused(this)" onfocusout="defocused(this)"></a>
                    </div>
                    <div class="ratings d-flex flex-row align-items-center">
                        <i class="bi bi-eye-fill"></i> <span> Category</span>
                    </div>
                    <div class="buttons d-flex flex-row mt-5 gap-3">
                        <a href="/MKT/ProductDetail/@Model.ProductCategory.First().ProductId" class="btn btn-outline-black ">Back</a>
                        <button type="submit" class="btn btn-secondary">Save</button>
                    </div>
                </div>
            }
            </div>
        
    </div>
    
</div>
<script>
    function changeImage(element) {

        var main_prodcut_image = document.getElementById('main_product_image');
        main_prodcut_image.src = element.src;
    }
    const deleteimg = (id) => {
        fetch('/MKT/DeleteImgProduct/' + id, {
            method: 'POST'
        }).then(
            console.log("add to cart " + id),
            location.reload()
        )
    }
   
    const imgnew = document.getElementById('main_product_image');
    const imgold = document.getElementById('newimg');
    
    imgold.onchange = evt => {
        const [file] = imgold.files
        if (file) {
            imgnew.src = URL.createObjectURL(file)
        }
    }
</script>