Project/Project/Models/Feedback.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feedback()
        {
            this.ImageFeedbacks = new HashSet<ImageFeedback>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public int RateStar { get; set; }
        public string Detail { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageFeedback> ImageFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Project/Project/Models/feedback/FeedbackViewModel.cs
using System.Collections.Generic;
using Project.Controllers;

namespace Project.Models.feedback
{
    public class FeedbackViewModel : HomeViewLayout
    {
        public bool IsEmpty { get; set; }
        public bool NotFeedback { get; set; }
        public List<OrderDetail> ListOrderDetails { get; set; }
        public Feedback Feedback { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public OrderDetail SelectOrderDetail { get; set; }
    }
}

Project/Project/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using Project.Models;
using System.Linq;
using System.Web;
using Project.Filter;
using Project.Models.feedback;

namespace Project.Controllers
{
    [AuthenticationFilter]
    [AuthorizationFilter(role: "customer")]
    public class FeedbackController : Controller
    {
        private ProjectEntities db = new ProjectEntities();

        public ActionResult Index(string orderId, string productId)
        {
            // init feedback model and get userId
            FeedbackViewModel layout = new FeedbackViewModel();
            int userid = 0;
            if (Session["userId"] != null)
            {
                userid = Int32.Parse(Session["userId"].ToString());
                var selectAccount = (from e in db.Accounts where e.Id == userid select e).ToList()[0];

                layout.Account = selectAccount;
            }

            userid = Int32.Parse(Session["userId"].ToString());

            // check if orderId and productId is null
            if (orderId == null || productId == null)
            {
                var listOrders =
                    (from order in db.Orders where order.AccountId == userid select order).OrderByDescending(e =>
                        e.CreatedAt);

                // check don't have order
                layout.IsEmpty = false;
                if (listOrders.ToList().Count == 0)
                {
                    layout.IsEmpty = true;
                    return View(layout);
                }
                else
                {
                    // get orderId and productId newest
                    var newest = listOrders.ToList()[0].OrderDetails.ToList()[0];
                    return Redirect(
                        $"/feedback?orderId={newest.OrderId}&productId={newest.ProductId}");
                }
            }
            else
            {
                // Parse orderId and productId
                int orderIdN = Int32.Parse(orderId);
                int productIdN = Int32.Parse(productId);

                // get orderDetail
                var temp = (from e in db.OrderDetails
                    where e.OrderId == orderIdN && e.ProductId == productIdN
                    select e).ToList()[0];

                layout.NotFeedback = temp.FeedbackId == null;
                if (temp.FeedbackId != null)
                {
                    var selectFeedback = temp.Feedback;
                    layout.Feedback = selectFeedback;
                }

                layout.OrderId = orderIdN;
                layout.ProductId = productIdN;

                var selectOrderDetail = (from e in db.OrderDetails
                    where e.OrderId == orderIdN && e.ProductId == productIdN
                    select e).ToList()[0];

                layout.SelectOrderDetail = selectOrderDetail;

                // get list order
                var listOrders =
                    (from order in db.Orders where order.AccountId == userid select order).OrderByDescending(e =>
                        e.CreatedAt);

                List<OrderDetail> listOrderDetails = new List<OrderDetail>();

                Array.ForEach(listOrders.ToArray(),
                    order =>
                        listOrderDetails.AddRange(order.OrderDetails.OrderByDescending(e => e.CreatedAt).ToList()));
                layout.ListOrderDetails = listOrderDetails;
            }

            return View(layout);
        }

        [HttpPost]
        public ActionResult SubmitFeedback(int productId, int orderId, int rate, string note, HttpPostedFileBase[] images)
        {
            List<string> listImage = new List<string>();
            foreach (var image in images)
            {
                // save image to temp folder
                string newFileName = DateTime.Now.Ticks + "_" + image.FileName;
                string path = Path.Combine(Server.MapPath("~/TempImageUpload"), newFileName);
                image.SaveAs(path);
                listImage.Add(path);
            }

            // upload to cloudinary and get url of image
            string[] urls = CloudinaryConfig.Upload(listImage.ToArray());

            // delete image from temp folder
            foreach (var path in listImage)
            {
                System.IO.File.Delete(path);
            }

            var newFeedback = db.Feedbacks.Add(new Feedback()
            {
                RateStar = rate,
                Detail = note,
                CreatedAt = DateTime.Now,
                UpdatedAt = DateTime.Now,
            });
            
            db.SaveChanges();

            var selectOrderDetail = db.OrderDetails.FirstOrDefault(e => e.OrderId == orderId && e.ProductId == productId);
            selectOrderDetail.FeedbackId = newFeedback.Id;
            selectOrderDetail.UpdatedAt = DateTime.Now;
            
            List<ImageFeedback> listImageFeedback = new List<ImageFeedback>();

            foreach (var url in urls)
            {
                listImageFeedback.Add(new ImageFeedback()
                {
                    Image = url,
                    FeedbackId = newFeedback.Id,
                    CreatedAt = DateTime.Now,
                    UpdatedAt = DateTime.Now,
                });
            }
            
            db.ImageFeedbacks.AddRange(listImageFeedback);

            db.SaveChanges();

            return Redirect($"/feedback?orderId={orderId}&productId={productId}");
        }
    }
}

Project/Project/Views/Feedback/Index.cshtml
@model Project.Models.feedback.FeedbackViewModel

@{
    ViewBag.Title = "title";
    Layout = "../Shared/_CommonLayout.cshtml";
}

<div class="container my-order">
    <div class="row text-center mt-4 mb-4">
        <strong>Feedback</strong>
    </div>
    @if (Model.IsEmpty)
    {
        <div class="row">
            <div class="col-12 fs-6">
                <i>Your order is currently empty</i>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-4 list-feedback">
                @if (Model.ListOrderDetails != null)
                {
                    foreach (var orderDetail in Model.ListOrderDetails)
                    {
                        <a href="@($"/feedback?orderId={orderDetail.OrderId}&productId={orderDetail.ProductId}")" class="feedback-item @((orderDetail.OrderId == Model.OrderId) && (orderDetail.ProductId == Model.ProductId) ? "feedback-item-selected" : "")">
                            <img src="@(orderDetail.Product.ImageProducts.ToList()[0]?.Image)" alt="">
                            <div class="feedback-item-content">
                                <p>
                                    <strong>@orderDetail.Product.Title</strong>
                                </p>
                                <div class="feedback-item-content-time">
                                    <p>
                                        <i>@orderDetail.CreatedAt</i>
                                    </p>
                                    @if (orderDetail.FeedbackId == null)
                                    {
                                        <div class="feedback-item-content-dot"></div>
                                    }
                                </div>
                            </div>
                        </a>
                    }
                }
            </div>
            <div class="col-8 feedback-detail">
                <div class="feedback-detail-information">
                    <img src="@(Model.SelectOrderDetail.Product.ImageProducts.ToList()[0]?.Image)" alt="">
                    <div>
                        <div>
                            <div>
                                <strong>@Model.SelectOrderDetail.Product.Title</strong>
                            </div>
                        </div>
                        <div class="fb-d-time">
                            <div>@Model.SelectOrderDetail.CreatedAt</div>
                            <div><strong>@Model.SelectOrderDetail.Quantity Items</strong> - <span style="color: red">$@(Model.SelectOrderDetail.Quantity * Model.SelectOrderDetail.SalePrice)</span></div>
                        </div>
                    </div>
                </div>
                <hr>
                @if (Model.SelectOrderDetail.FeedbackId == null)
                {
                    <div>
                        @using (Html.BeginForm("SubmitFeedback", "Feedback", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <div class="input-rate row">
                                <div class="col-1">
                                    <strong>Rate: </strong>
                                </div>
                                <div class="rate-star col-5">
                                    <button type="button" onclick="changeRateStar(1)">
                                        <img id="image-rate-1"
                                             src="https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png"
                                             alt="1"/>
                                    </button>
                                    <button type="button" onclick="changeRateStar(2)">
                                        <img id="image-rate-2"
                                             src="https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png"
                                             alt="2"/>
                                    </button>
                                    <button type="button" onclick="changeRateStar(3)">
                                        <img id="image-rate-3"
                                             src="https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png"
                                             alt="3"/>
                                    </button>
                                    <button type="button" onclick="changeRateStar(4)">
                                        <img id="image-rate-4"
                                             src="https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png"
                                             alt="4"/>
                                    </button>
                                    <button type="button" onclick="changeRateStar(5)">
                                        <img id="image-rate-5"
                                             src="https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png"
                                             alt="5"/>
                                    </button>
                                    <input type="number" name="rate" value="5" id="star">
                                    <input type="number" value="@(Model.SelectOrderDetail.OrderId)" name="orderId">
                                    <input type="number" value="@(Model.SelectOrderDetail.ProductId)" name="productId">
                                </div>
                            </div>
                            <div class="input-note row">
                                <div class="col-1">
                                    <strong>Note: </strong>
                                </div>
                                <div class="col-5">
                                    <textarea name="note" id="asd" cols="30" rows="6"></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-1">
                                    <strong>Image:</strong>
                                </div>
                                <div class="col-5">
                                    <input type="file" name="images" id="image" accept="image/*" multiple="multiple" required>
                                </div>
                            </div>
                            <div class="row mt-4">
                                <div class="col-1"></div>
                                <div class="col-5">
                                    <button class="feedback-button-submit" type="submit">Submit feedback</button>
                                </div>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <div class="row">
                        <div class="col-1">
                            <strong>Rate: </strong>
                        </div>
                        <div class="col-5 rate-star">
                            @for (int i = 0; i < 5; i++)
                            {
                                if (i < Model.SelectOrderDetail.Feedback.RateStar)
                                {
                                    <img src="https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png"/>
                                }
                                else
                                {
                                    <img src="https://img.icons8.com/ios-glyphs/60/f1f1f1/star--v1.png"/>
                                }
                            }
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-1">
                            <strong>Note: </strong>
                        </div>
                        <div class="col-5">
                            @Model.SelectOrderDetail.Feedback.Detail
                        </div>
                    </div>
                    <div class="row mt-2">
                        <div class="col-1">
                            <strong>Images: </strong>
                        </div>
                        <div class="col-5">
                            @for (int i = 0; i < Model.SelectOrderDetail.Feedback.ImageFeedbacks.Count; i++)
                            {
                                <img class="image-feedback-o" src="@Model.SelectOrderDetail.Feedback.ImageFeedbacks.ToList()[i].Image"/>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
    }
</div>

<script>
  const changeRateStar = (star) => {
    const normalStar = 'https://img.icons8.com/ios-glyphs/60/f1f1f1/star--v1.png'
    const goldStar = 'https://img.icons8.com/ios-glyphs/60/ffbb00/star--v1.png'

    for (let i = 0; i < 5; i++) {
      if (i < star) {
        document.getElementById(`image-rate-${i + 1}`).src = goldStar
      } else {
        document.getElementById(`image-rate-${i + 1}`).src = normalStar
      }
    }

    document.getElementById('star').value = star
  }
</script>