Project/Project/Models/Blog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Detail { get; set; }
        public int CountView { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Account Account { get; set; }
    }
}

Project/Project/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Web.Mvc;
using Project.Models;
using System.Linq;
using Project.Filter;


namespace Project.Controllers
{
    
    public class BlogController : Controller
    {
        private ProjectEntities db = new ProjectEntities();
        // GET: Blog
        /*[AuthenticationFilter]
        [AuthorizationFilter("customer")]*/
        public ActionResult Index(int? id)
        {
            BlogListViewModel viewModelBlog = new BlogListViewModel();
            if (Session["userId"] != null)
            {
                int userid = Int32.Parse(Session["userId"].ToString());
                var selectAccount = (from e in db.Accounts where e.Id == userid select e).FirstOrDefault();
                viewModelBlog.Account = selectAccount;
            }
            if (id == null || id == 1)
            {
                ViewBag.Index = 1;
            }
            else
            { ViewBag.Index = id; }

            if (id == null)
            {
               
                var lb = db.Blogs.Take(9).ToList();
                if (lb == null)
                {
                    return new EmptyResult();
                }
                viewModelBlog.CountList = db.Blogs.ToList().Count();
                viewModelBlog.BlogList = lb;
                return View(viewModelBlog);
            }
            else {               
                    var lb = (from e in db.Blogs select e).OrderBy(i => 0).Skip((id.GetValueOrDefault() - 1) * 9).Take(9).ToList();
                    if (lb == null)
                    {
                        return new EmptyResult();
                    }
                    viewModelBlog.CountList = db.Blogs.Count();
                    viewModelBlog.BlogList = lb;
                    
                    return View(viewModelBlog);
            } 
        }
        public ActionResult BlogDetail(int? id)
        {
            Blog a = new Blog();
          
            BlogListViewModel blm = new BlogListViewModel();
            if (Session["userId"] != null)
            {
                int userid = Int32.Parse(Session["userId"].ToString());
                var selectAccount = (from e in db.Accounts where e.Id == userid select e).ToList()[0];

                blm.Account = selectAccount;
                
                
            }
            //get detail post
            var detail = (from x in db.Blogs where x.Id == id select x).First();


            //update countview
            detail.CountView = detail.CountView + 1;
            db.SaveChanges();

            a.Id = detail.Id;
            a.Title = detail.Title;
            a.AuthorId = detail.AuthorId;
            a.CreatedAt = detail.CreatedAt;
            a.UpdatedAt = detail.UpdatedAt;
            a.Detail = detail.Detail;
            a.Image = detail.Image;
            a.CountView = detail.CountView;
            blm.blog = a;
            

            //get author's post infor
            int author_id = detail.AuthorId;
            var author = (from x in db.Accounts where x.Id == author_id select x).First();
            Account au = new Account();
            au.Id = author.Id;
            au.FullName = author.FullName;
            au.Image = author.Image;
            blm.Author = au;

            //get 3 lastest post
            Dictionary < Blog, Account > last_post = new Dictionary<Blog, Account>();
            var lastest_post = db.Blogs.Take(3).OrderByDescending(x => x.Id).ToList();
            if (lastest_post != null)
            {
                foreach(var item in lastest_post)
                {
                    int au_id = item.AuthorId;
                    Account aut = db.Accounts.Where(x => x.Id == au_id).First();
                    last_post.Add(item,aut);
                } 
            }
            blm.LastestPost = last_post;

            //get trending post
            Dictionary<Blog, Account> trending = new Dictionary<Blog, Account>();
            var trending_post = db.Blogs.Take(2).OrderByDescending(x => x.CountView).ToList();
            if(trending_post != null)
            {
                foreach(var item in trending_post)
                {
                    int au_id_trend = item.AuthorId;
                    Account aut = db.Accounts.Where(x => x.Id == au_id_trend).First();
                    trending.Add(item, aut);
                }
            }
            blm.TrendingPost = trending;

            return View(blm);
        }

    }
}

Project/Project/Views/Blog/BlogDetail.cshtml
@{
    ViewBag.Title = "BlogDetail";
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
}

@model Project.Models.BlogListViewModel
<body>
    <div class="blog-single gray-bg">
        <div class="container">
            <div class="row align-items-start">
                <div class="col-lg-8 m-15px-tb">
                    <article class="article">
                        <div class="article-img">
                            <img class="blog-img__default" src="@Model.blog.Image" title="" alt="">
                        </div>
                        <div class="article-title">
                            <h6><a href="#">Lifestyle</a></h6>
                            <h2>@Model.blog.Title</h2>
                            <div class="media">
                                <div class="avatar">
                                    <img src="@Model.Author.Image" title="" alt="">
                                </div>
                                <div class="media-body">
                                    <label>@Model.Author.FullName</label>
                                    <span>@Model.blog.UpdatedAt.ToString("dd MMM yyyy")</span>
                                </div>
                            </div>
                        </div>
                        <div class="article-content">
                            <p>
                                @Model.blog.Detail
                            </p>
                            
                        </div>
                    </article>
                </div>
                <div class="col-lg-4 m-15px-tb blog-aside">
                    <!-- Author -->
                    <div class="widget widget-author">
                        <div class="widget-title">
                            <h3>Author</h3>
                        </div>
                        <div class="widget-body">
                            <div class="media align-items-center">
                                <div class="avatar">
                                    <img src="@Model.Author.Image" title="" alt="">
                                </div>
                                <div class="media-body">
                                    <h6>Written by<br> @Model.Author.FullName</h6>
                                </div>
                            </div>                            
                        </div>
                    </div>
                    <!-- End Author -->
                    <!-- Trending Post -->
                    <div class="widget widget-post">
                        <div class="widget-title">
                            <h3>Trending Now</h3>
                        </div>
                        <div class="widget-body">
                            @if (Model.TrendingPost != null)
                            {
                            foreach (var item in Model.TrendingPost)
                            {                                
                                    <div class="latest-post-aside media">
                                        <div class="lpa-left media-body">
                                            <div class="lpa-title">
                                                <h5><a href="../Blog/BlogDetail?id=@item.Key.Id">@item.Key.Title</a></h5>
                                            </div>
                                            <div class="lpa-meta">
                                                <a class="name" href="#">
                                                    @item.Value.FullName
                                                </a>
                                                <a class="date" href="#">
                                                    @item.Value.UpdatedAt.ToString("dd MMM yyyy")
                                                </a>
                                            </div>
                                        </div>
                                        <div class="lpa-right">
                                            <a href="#">
                                                <img src="@item.Key.Image" title="" alt="">
                                            </a>
                                        </div>
                                    </div>
                               
                            }}
                        </div>
                    </div>
                    <!-- End Trending Post -->
                    <!-- Latest Post -->
                    <div class="widget widget-latest-post">
                        <div class="widget-title">
                            <h3>Latest Post</h3>
                        </div>
                        @if (Model.LastestPost != null)
                        {
                        foreach (var item in Model.LastestPost)
                        {
                            <div class="widget-body">
                                <div class="latest-post-aside media">
                                    <div class="lpa-left media-body">
                                        <div class="lpa-title">
                                            <h5><a href="../Blog/BlogDetail?id=@item.Key.Id">@item.Key.Title</a></h5>
                                        </div>
                                        <div class="lpa-meta">
                                            <a class="name" href="#">
                                                @item.Value.FullName
                                            </a>
                                            <a class="date" href="#">
                                                @item.Value.UpdatedAt.ToString("dd MMM yyyy")
                                            </a>
                                        </div>
                                    </div>
                                    <div class="lpa-right">
                                        <a href="#">
                                            <img src="@item.Key.Image" title="" alt="">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        }}
                    </div>
                    <!-- End Latest Post -->
                </div>
            </div>
        </div>
    </div>
</body>

Project/Project/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CommonLayout.cshtml";
}

@model Project.Models.BlogListViewModel

<body>
    <div class="blog">
        <div class="container">
            <div class="blog-container">

                @foreach (var item in Model.BlogList)
                {
                    <div class="blog-list">
                        <div class="left-content">
                            <p class="left-content__desc">New post</p>
                            <img class="img" src="@item.Image" alt="blog">
                            <h3 class="left-content__ttl">@item.Title</h3>
                        </div>

                        <div class="right-content">
                            <div class="right-content__desc">
                                @item.Detail
                            </div>
                            <a class="blog-moredesc" href="@Url.Action("BlogDetail","Blog")?id=@item.Id">Read more</a>
                        </div>
                    </div>
                }

            </div>
            <div class="blog-pagination">
                @if (ViewBag.Index != null && ViewBag.Index > 1)
                {
                    <a href="/Blog/Index/@(ViewBag.Index-1)">Previous</a>
                }
                else
                {
                    <a href="#">Previous</a>
                }

                @for (double i = 1; i < (((double)Model.CountList) / 9) + 1; i++)
                {
                    if (i == ViewBag.Index)
                    {
                        <a style="background-color:khaki"  href="/Blog/Index/@(i)">@i</a>
                    }
                    else
                    {
                        <a href="/Blog/Index/@(i)">@i</a>
                    }
                }
                @if (ViewBag.Index != null && ViewBag.Index * 9 < Model.CountList)
                {
                    <a href="/Blog/Index/@(ViewBag.Index + 1)">Next</a>
                }
                else
                {
                    <a href="#">Next</a>
                }
            </div>
        </div>
    </div>
</body>